name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test & Coverage
      run: dotnet test --no-restore --nologo --logger "console;verbosity=normal" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage/opencover-coverage.xml
    - name: Upload coverage to Codecov
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v4
      with:
        name: codecov-tulip
        file: ./tests/Tulip.NETCore.Tests/coverage/opencover-coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true
